### ISSUE TITLE
CLJC logo

### ISSUE THREAD

**Issue by danielcompton** [cljs/logo#1]
Hi folks

Inspired by your logo, I've created a CLJC derivative. Firstly, I hope you don't mind. Also, would you want to include it in this repo so they can stay together? It takes the design of the CLJS logo and some colours from the CLJ logo to combine them together. I'm happy to put together a PR with all of the files if you'd like.

<img src="https://cloud.githubusercontent.com/assets/811954/17041291/428399c4-4ff9-11e6-9c07-c43364261700.png" width="100px">

**Comment by shaunlebron** [comment]
Hi Daniel, I suppose the objective is to create a .cljc file icon for editors to display?

**Comment by danielcompton** [comment]
Yep that's the one.

**Comment by oakmac** [comment]
Hi :)

I'm out of country right now, but I'll give this a reply when I get back.

Chris

**Comment by shaunlebron** [comment]
Not in favor of this offshoot. Logos should be meaningfully discernible.  The letter change is too subtle, the reflected hues arbitrary, and the separation of `cl` `jc` becomes confused.

<img src="https://cloud.githubusercontent.com/assets/116838/17079105/ca2e202e-50cb-11e6-8d68-7cd72cca0794.png" width="100px"> <img src="https://raw.githubusercontent.com/cljs/logo/master/cljs.png" width="100px"> <img src="https://cloud.githubusercontent.com/assets/811954/17041291/428399c4-4ff9-11e6-9c07-c43364261700.png" width="100px">

I would avoid subtle brand changes, and do something simpler.  The reader conditional `#?` is cljc's defining feature.  @tonsky's [FiraCode](https://github.com/tonsky/FiraCode) ligature for `#?` is a good start:

<img src="https://cloud.githubusercontent.com/assets/116838/17079155/26583ee2-50cd-11e6-9e58-cbdc2516e5fa.png" width="100px"> <img src="https://cloud.githubusercontent.com/assets/116838/17079201/53725dee-50ce-11e6-9837-7c23279bfde2.png" width="100px"> <img src="https://cloud.githubusercontent.com/assets/116838/17079015/9ba39fce-50c9-11e6-9b5f-b7c59c704c3d.png" width="100px">

**Comment by tonsky** [comment]
Couple of thoughts, if you don’t mind
- I like brighter colors!
- if we want for this to be an icon for a file type in an editor, then it’s a good thing they look similar but distinguishable enough
- in cljs logo `js` was highlighted for a reason (JS = javascript), in cljc it has lost its meaning (BTW does anybody knows what `c` in cljc stands for?)
- `#?` makes a very good point, but emotionally it doesn’t relate to me very well. First, question mark in a logo communicates uncertainty (at least for me). Second, as I’ve been writing a lot of  CLJC, `#?` is a construct you’re happy to avoid (because it complicates things), so promoting it on a logo is kind of undesirable (at least for me, it’s like putting NPE on Java logo :)

Sorry I have nothing specific to offer, but I thought some critique might be valuable as well. I understand how hard it is to design a logo, and I truly wish everything Clojure-related had a cool logo. While we’re not in a hurry, let’s give it some thought?

**Comment by tonsky** [comment]
<img src=https://cloud.githubusercontent.com/assets/285292/17083904/a9b37450-51e0-11e6-8e52-2bfde3867419.png width=100 height=100>

m?

**Comment by shaunlebron** [comment]
@tonsky good points!  I agree about the emotional communication of a question mark.  Comparing a null-pointer-exception to a reader conditional is nonsense though, lol.  Also, [we'll see](https://twitter.com/shaunlebron/status/757255715786334208) what the `c` stands for.

not crazy about any of the logos, including mine. a designer could make the ideas work better.  we should also keep in mind that this is just a file extension logo, not a community brand.

**Comment by danielcompton** [comment]
> the reflected hues arbitrary

The colours were taken from the Clojure logo.

I like @tonsky's one more personally with the angles and separating the `c` out. 

Here's an example of how the current two look in Cursive:

<img width="144" alt="screenshot of intellij idea 25-07-16 2-38-06 pm" src="https://cloud.githubusercontent.com/assets/811954/17088936/7cd840ce-5275-11e6-96b5-5a56755280bc.png">

Any distinction would need to quite clear, perhaps reflecting the colours in @tonsky's one so blue is on the left hand side to contrast with CLJS's logo where it is on the right?

**Comment by tonsky** [comment]
Clearly needs white background, same as clj has

**Comment by shaunlebron** [comment]
already asked colin here: https://twitter.com/shaunlebron/status/757414958195814401

Also, the `c` in cljc stands for common: https://twitter.com/puredanger/status/757265908490379265

**Comment by oakmac** [comment]
Finally getting around to this. I agree with @shaunlebron's points above: I am not a fan of this variation. The changes seem like arbitrary modifications to the CLJS logo; not something that reflects the nature of cljc.

I added some [design notes](https://github.com/cljs/logo#design) to the README to provide some context behind the decisions that went into the CLJS logo. Maybe something similar could be done for cljc and then design accordingly?

To be clear: the CLJS logo is licensed under a [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), so you are completely free to modify it how you want. But this doesn't have "my blessing", so to speak.

Apologies for this negative comment; design is hard :)

**Comment by cursive-ghost** [comment]
In case anyone is interested, here's what I went with for Cursive:

![screen shot 2017-05-23 at 15 26 18](https://cloud.githubusercontent.com/assets/5589171/26337449/e45a5daa-3fcc-11e7-833d-a6b01a903673.png)

Clearly I'm no designer, but bear with me. My needs are quite different to something like a laptop sticker, I'm not really worried about communicating uncertainty with the question mark or anything like that. The most important thing for Cursive is that the files be easily distinguishable by their icon, which for non-retina screens is 16x16 pixels. I've just tidied up the CLJS icon so it looks better at that resolution, and I made this one up while I was at it. The text is located so it aligns better with the pixel grid:

![screen shot 2017-05-23 at 15 26 01](https://cloud.githubusercontent.com/assets/5589171/26337452/ea0559ee-3fcc-11e7-973f-97c64b464b63.png)

Here's what the 3 icons look like now, for retina/non-retina in light and dark themes:

![screen shot 2017-05-23 at 15 28 14](https://cloud.githubusercontent.com/assets/5589171/26337460/f50c0504-3fcc-11e7-8ef9-7add210eeea0.png)

![screen shot 2017-05-23 at 15 28 41](https://cloud.githubusercontent.com/assets/5589171/26337462/f6f8aa5c-3fcc-11e7-8b8e-a982a501c977.png)

<img width="137" alt="screen shot 2017-05-23 at 15 30 15" src="https://cloud.githubusercontent.com/assets/5589171/26337464/f9b8fb20-3fcc-11e7-8c78-e188205ce431.png">

<img width="147" alt="screen shot 2017-05-23 at 15 29 52" src="https://cloud.githubusercontent.com/assets/5589171/26337465/fbaf3e80-3fcc-11e7-9e0e-6cd890b5e1a4.png">

Under the dark theme it could really do with a white border around it, but I'm out of pixels.

Edit: my OCD wouldn't let me, so I shuffled things around and added a border.

**Comment by hcarvalhoalves** [comment]
@cursive-ide I find the icon still a little hard to read, but the square format should be enough to distinguish
