### ISSUE TITLE
License

### ISSUE THREAD

**Issue by puredanger** [cljs/logo#2]
Rich is ok with adopting this cljs logo as the official logo for ClojureScript but would prefer a license better suited to a logo than MIT, which is [written](https://opensource.org/licenses/MIT) in terms of software and docs.

I would humbly suggest that Creative Commons provides licenses that are perfectly applicable however and seem to meet your intentions. Worth considering are [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/), [CC-SA](http://creativecommons.org/licenses/by/4.0/), and [CC-BY-SA](http://creativecommons.org/licenses/by-sa/4.0/). I think CC0 is probably the best match to your intent with MIT (use as is without restriction).

**Comment by oakmac** [comment]
Wonderful news!

I have been thinking for a while that a CC0 license might be more appropriate for the logo. I made that change with [commit #552ae1](https://github.com/cljs/logo/commit/552ae10a7764847e6bb8d34c3fa85d7bb2ed3826)

**Comment by puredanger** [comment]
Excellent, thanks!

**Comment by shaunlebron** [comment]
@puredanger can this repo be moved to the clojure org?

(the cljs org used to be a collection of stuff, but is now just home to the api docs)

**Comment by oakmac** [comment]
@shaunlebron I am willing to take ownership of this repo if you do not want it under the cljs org

**Comment by shaunlebron** [comment]
I think the official logo belongs on the official org, but we can move it to yours if it doesn’t make it through.

**Comment by puredanger** [comment]
I'm check, will let you know next week.

**Comment by puredanger** [comment]
I'm check, will let you know next week.

**Comment by puredanger** [comment]
Happy to move it over to clojure org if you want to

**Comment by shaunlebron** [comment]
@puredanger Sorry for the run around, we chose to move it to the inventor’s account instead.  Thank you!

**Comment by puredanger** [comment]
👍
