### ISSUE TITLE
Correct scaling artifact due to stroke-width

### ISSUE THREAD

**Issue by shaunlebron** [cljs/logo#3]
I've seen this scaling artifact before.  When you downscale the logo svg, the `stroke-width` of the parens does not scale with the rest of the logo:

![cljskey-artifact](https://pbs.twimg.com/media/CqohOI-WYAAxX98.jpg:large)

We can redefine the parens without using stroke-width, by explicitly defining the outline path.  This is the code to replace:

``` svg
<path stroke="#96CA4B" stroke-width="6" fill="#96CA4B" d="M183,376.7 C91.8,368.6 20,291.7 20,198.4 C20,105.1 91.8,28.3 183,20.2 L183,0.1 C80.7,8.3 0,94.1 0,198.5 C0,302.9 80.7,388.7 183,396.9 L183,376.7 L183,376.7 Z"></path>
<path stroke="#5F7FBF" stroke-width="6" fill="#5F7FBF" d="M215,0.1 L215,20.2 C306.2,28.3 378,105.2 378,198.5 C378,291.8 306.2,368.7 215,376.8 L215,396.9 C317.3,388.7 398,302.9 398,198.5 C398,94.1 317.3,8.3 215,0.1 L215,0.1 Z"></path>
```

**Comment by shaunlebron** [comment]
The regular scaling context in a browser will appropriately scale the stroke-width as expected.

The bug shown above will only happen when you resize inside of an editor, where paths are transformed, and stroke-widths are preserved, as intended.  For example, in Sketch, downscaling the logo will produce this:

<img width="832" alt="screen shot 2016-08-24 at 11 04 37 pm" src="https://cloud.githubusercontent.com/assets/116838/17956399/291cbf86-6a4f-11e6-9dce-cbf7417acbf6.png">

**Comment by oakmac** [comment]
Thanks for looking into this :)
